-- MySQL Script generated by MySQL Workbench
-- Sat Mar 23 18:59:57 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema librarydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `librarydb` ;

-- -----------------------------------------------------
-- Schema librarydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `librarydb` DEFAULT CHARACTER SET utf8 ;
USE `librarydb` ;

-- -----------------------------------------------------
-- Table `librarydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `librarydb`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(20) NOT NULL,
  `lastname` VARCHAR(20) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `category` VARCHAR(20) NOT NULL,
  `image` BLOB NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `librarydb`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `librarydb`.`products` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(25) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `image` BLOB NULL,
  `category` VARCHAR(25) NOT NULL,
  `color` VARCHAR(25) NULL,
  `price` DOUBLE NOT NULL,
  PRIMARY KEY (`product_id`),
  UNIQUE INDEX `product_id_UNIQUE` (`product_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `librarydb`.`carts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `librarydb`.`carts` (
  `cart_id` INT NOT NULL AUTO_INCREMENT,
  `quantity` INT NOT NULL,
  `subtotal` DOUBLE NOT NULL,
  `users_user_id` INT NOT NULL,
  `products_product_id` INT NOT NULL,
  PRIMARY KEY (`cart_id`, `users_user_id`, `products_product_id`),
  UNIQUE INDEX `cart_id_UNIQUE` (`cart_id` ASC) VISIBLE,
  INDEX `fk_carts_users_idx` (`users_user_id` ASC) VISIBLE,
  INDEX `fk_carts_products1_idx` (`products_product_id` ASC) VISIBLE,
  CONSTRAINT `fk_carts_users`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `librarydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carts_products1`
    FOREIGN KEY (`products_product_id`)
    REFERENCES `librarydb`.`products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
